#!/bin/bash
python="/usr/bin/time -f %e python"
if [ ! -f data/fast_algorithms.pkl ]; then
	$python fast-node-encoding/scripts/fast_merge_pickles_to_pickle.py crawler/data/new_data.pkl data/fast_algorithms.pkl
fi
if [ ! -f data/fast_algorithms_nodes.pkl ]; then
	$python fast-node-encoding/scripts/fast_pickle_file_to_nodes.py data/fast_algorithms.pkl data/fast_algorithms_nodes.pkl
fi
if [ ! -f data/fast_pretrained_vectors.pkl ]; then
	$python fast-node-encoding/fast_train.py data/fast_algorithms_nodes.pkl data/fast_pretrained_vectors.pkl
fi
if [ ! -f data/fast_algorithms_trees.pkl ]; then
	$python fast-node-encoding/scripts/fast_pickle_file_to_training_trees.py data/fast_algorithms.pkl data/fast_algorithms_trees.pkl
fi
docker build -t tbcnn docker
docker run -w /root -v $(pwd):/root -it tbcnn $python fast-tbcnn/train_tbcnn.py data/fast_algorithms_trees.pkl ./data/fast_pretrained_vectors.pkl
docker run -w /root -v $(pwd):/root -it tbcnn $python fast-tbcnn/test_tbcnn.py data/fast_algorithms_trees.pkl ./data/fast_pretrained_vectors.pkl
