#!/bin/bash
python="/usr/bin/time -f %e python"
docker build -t tbcnn docker
if [ ! -f data/java_algorithms.pkl ]; then
	$python fast-node-encoding/scripts/fast_merge_pickles_to_pickle.py crawler/data/new_data.java.pkl data/java_algorithms.pkl
fi
if [ ! -f data/java_algorithms_nodes.pkl ]; then
	$python fast-node-encoding/scripts/fast_pickle_file_to_nodes.py data/java_algorithms.pkl data/java_algorithms_nodes.pkl
fi
if [ ! -f data/java_pretrained_vectors.pkl ]; then
	docker run -w /root -v $(pwd):/root -it tbcnn $python fast-node-encoding/train.py data/java_algorithms_nodes.pkl data/java_pretrained_vectors.pkl
fi
if [ ! -f data/java_algorithms_trees.pkl ]; then
	$python fast-node-encoding/scripts/fast_pickle_file_to_training_trees.py data/java_algorithms.pkl data/java_algorithms_trees.pkl
fi
docker run -w /root -v $(pwd):/root -it tbcnn $python fast-tbcnn/train_tbcnn.py data/java_algorithms_trees.pkl ./data/java_pretrained_vectors.pkl
#docker run -w /root -v $(pwd):/root -it tbcnn $python fast-tbcnn/test_tbcnn.py data/fast_algorithms_trees.pkl ./data/fast_pretrained_vectors.pkl
