#!/bin/bash
python="/usr/bin/time -f %e python"
docker build -t tbcnn docker
if [ ! -f data/pku_algorithms.pkl ]; then
	$python fast-node-encoding/scripts/fast_merge_pickles_to_pickle.py data/ProgramData data/pku_algorithms.pkl
fi
if [ ! -f data/pku_algorithms_nodes.pkl ]; then
	$python fast-node-encoding/scripts/fast_pickle_file_to_nodes.py data/pku_algorithms.pkl data/pku_algorithms_nodes.pkl
fi
if [ ! -f data/pku_pretrained_vectors.pkl ]; then
	docker run -w /root -v $(pwd):/root -it tbcnn $python fast-node-encoding/fast_train.py data/pku_algorithms_nodes.pkl data/pku_pretrained_vectors.pkl
fi
if [ ! -f data/pku_algorithms_trees.pkl ]; then
	$python fast-node-encoding/scripts/fast_pickle_file_to_training_trees.py data/pku_algorithms.pkl data/pku_algorithms_trees.pkl
fi
docker run -w /root -v $(pwd):/root -it tbcnn $python fast-tbcnn/train_tbcnn.py data/pku_algorithms_trees.pkl ./data/pku_pretrained_vectors.pkl
docker run -w /root -v $(pwd):/root -it tbcnn $python fast-tbcnn/test_tbcnn.py data/pku_algorithms_trees.pkl ./data/pku_pretrained_vectors.pkl
