#!/bin/bash
if [ ! -f /tmp/convert ]; then
	cat > /tmp/convert <<EOF
#!/bin/bash
src_file=\$1
pb_file=\$src_file.pb
if [ ! -f \$pb_file ]; then
	fast \$src_file \$pb_file
fi
pkl_file=\$src_file.pkl
if [ -f \$pb_file -a ! -f \$pkl_file ]; then
	fast \$pb_file \$pkl_file
fi
EOF
	chmod +x /tmp/convert
fi

ls new_data | while read f; do
	if [ -d $f ]; then
		parallel --eta /tmp/convert ::: $f/cpp/*.cpp $f/java/*.java
	fi
done
