#!/bin/sh
if [ ! -f /tmp/convert ]; then
	cat > /tmp/convert <<EOF
#!/bin/bash
src_file=\$1
mkdir -p /ast/\$(dirname \$src_file)
if [ "\${src_file/.python/}" == "\${src_file}" ]; then
	#json_file=/ast/\$src_file.json
	pkl_file=/ast/\$src_file.pkl
	if [ ! -f \$pkl_file ]; then
		#fbs_file=/ast/\$src_file.fbs
		#fast -S -G \$src_file \$fbs_file > /dev/null
		fast -S \$src_file \$pkl_file > /dev/null
		#ggnn \$fbs_file \$json_file
		#rm -f \$fbs_file
	fi
fi
EOF
	chmod +x /tmp/convert
fi
cd /code 
ls | while read f; do
	if [ -d $f ]; then
		parallel --eta /tmp/convert ::: $f/*/*
	fi
done
cd -
