/*
 * Automatically generated by jrpcgen 1.0.7 on 29.05.07 21:34
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class LINKEDLIST implements XdrAble, java.io.Serializable {
    protected int foo;
    protected LINKEDLIST next;

    private static final long serialVersionUID = -9187504517170663946L;

    public void setFoo(int x) { this.foo = x; }
    public int getFoo() { return this.foo; }

    public void setNext(LINKEDLIST x) { this.next = x; }
    public LINKEDLIST getNext() { return this.next; }

    public LINKEDLIST() {
    }

    public LINKEDLIST(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        LINKEDLIST $this = this;
        do {
            xdr.xdrEncodeInt($this.foo);
            $this = $this.next;
            xdr.xdrEncodeBoolean($this != null);
        } while ( $this != null );
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        LINKEDLIST $this = this;
        LINKEDLIST $next;
        do {
            $this.foo = xdr.xdrDecodeInt();
            $next = xdr.xdrDecodeBoolean() ? new LINKEDLIST() : null;
            $this.next = $next;
            $this = $next;
        } while ( $this != null );
    }

}
// End of LINKEDLIST.java
